src/accounts/api/urls.py
from django.conf.urls import url
from django.views.generic.base import RedirectView

from tweets.api.views import (
    TweetListAPIView,
    )

urlpatterns = [
    url(r'^(?P<username>[\w.@+-]+)/tweet/$', TweetListAPIView.as_view(), name='list'), # /api/tweet/
]

src/accounts/urls.py
from django.conf.urls import url
from django.views.generic.base import RedirectView
from .views import UserDetailView, UserFollowView

urlpatterns = [
	#url(r'^$', RedirectView.as_view(url="/")),
    #url(r'^search/$', TweetListView.as_view(), name='list'),
    #url(r'^create/$', TweetCreateView.as_view(), name='create'),
    url(r'^(?P<username>[\w.@+-]+)/$', UserDetailView.as_view(), name='detail'),
    url(r'^(?P<username>[\w.@+-]+)/follow/$', UserFollowView.as_view(), name='follow'),
    #url(r'^(?P<pk>\d+)/update/$', TweetUpdateView.as_view(), name='update'),
    #url(r'^(?P<pk>\d+)/delete/$', TweetDeleteView.as_view(), name='delete'),
    
]

src/tweet/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import UserRegisterView
from hashtags.api.views import TagTweetAPIView
from hashtags.views import HashTagView
from tweets.api.views import SearchTweetAPIView
from tweets.views import TweetListView
from .views import home, SearchView

urlpatterns = [
    url(r'^admin/', admin.site.urls), 
    url(r'^$', TweetListView.as_view(), name='home'), 
    url(r'^search/$', SearchView.as_view(), name='search'), 
    url(r'^tags/(?P<hashtag>.*)/$', HashTagView.as_view(), name='hashtag'),
    url(r'^tweet/', include('tweets.urls', namespace='tweet')),
    url(r'^api/tags/(?P<hashtag>.*)/$', TagTweetAPIView.as_view(), name='tag-tweet-api'), 
    url(r'^api/search/$', SearchTweetAPIView.as_view(), name='search-api'), 
    url(r'^api/tweet/', include('tweets.api.urls', namespace='tweet-api')),
    url(r'^api/', include('accounts.api.urls', namespace='profiles-api')),
    url(r'^register/$', UserRegisterView.as_view(), name='register'), 
    url(r'^', include('django.contrib.auth.urls')),
    url(r'^', include('accounts.urls', namespace='profiles'))
]

if settings.DEBUG:
    urlpatterns+=(static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

src/accounts/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.urls import reverse_lazy

# Create your models here.
class UserProfileManager(models.Manager):
	use_for_related_fields = True
	def all(self):
		qs = self.get_queryset().all()
		try:
			if self.instance:
				qs = qs.exclude(user = self.instance)
		except:
			pass
		return qs

	def toggle_follow(self, user, to_toggle_user):
		user_profile, created = userProfile.objects.get_or_create(user=user)
		if to_toggle_user in user_profile.following.all():
			user_profile.following.remove(to_toggle_user)
			added = False
		else:
			user_profile.following.add(to_toggle_user)
			added = True
		return added

	def is_following(self, user, followed_by_user):
		user_profile, created = userProfile.objects.get_or_create(user=user)
		if created:
			return False
		if followed_by_user in user_profile.following.all():
			return True
		return False

	def recommended(self, user, limit_to=10):
	    print(user)
	    profile = user.profile
	    following = profile.following.all()
	    following = profile.get_following()
	    qs = self.get_queryset().exclude(user__in=following).exclude(user__in=following).exclude(id=profile.id).order_by("?")[:limit_to]
	    return qs

class userProfile(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='profile')
	following = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='followed_by')

	objects = UserProfileManager()

	def __str__(self):
		return str(self.following.all().count())

	def get_following(self):
		users = self.following.all()
		return users.exclude(username=self.user.username)

	def get_follow_url(self):
		return reverse_lazy("profiles:follow", kwargs={"username":self.user.username})

	def get_absolute_url(self):
		return reverse_lazy("profiles:detail", kwargs={"username":self.user.username})
                

def post_save_user_reciever(sender, instance, created, *args, **kwargs):
    if created:
        new_profile = userProfile.objects.get_or_create(user=instance)

post_save.connect(post_save_user_reciever, sender=settings.AUTH_USER_MODEL)

src/tweets/models.py
import re
from django.conf import settings
from django.urls import reverse
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models.signals import post_save
from django.utils import timezone

# Create your models here.
from hashtags.signals import parsed_hashtags
from .validators import validate_content


# model manager

class TweetManager(models.Manager):
    def retweet(self, user, parent_obj):
        if parent_obj.parent:
            og_parent = parent_obj.parent
        else:
            og_parent = parent_obj
        
        qs = self.get_queryset().filter(
                user=user, parent=og_parent
                ).filter(
                    timestamp__year=timezone.now().year,
                    timestamp__month=timezone.now().month,
                    timestamp__day=timezone.now().day,
                    reply=False,
                )
        if qs.exists():
            return None

        obj = self.model(
                parent = og_parent,
                user = user,
                content = parent_obj.content,
            )
        obj.save()

        return obj

    def like_toggle(self, user, tweet_obj):
        if user in tweet_obj.liked.all():
            is_liked = False
            tweet_obj.liked.remove(user)
        else:
            is_liked = True
            tweet_obj.liked.add(user)
        return is_liked



class Tweet(models.Model):
    parent      = models.ForeignKey("self", blank=True, null=True)
    user        = models.ForeignKey(settings.AUTH_USER_MODEL)
    content     = models.CharField(max_length=140, validators=[validate_content])
    liked       = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name='liked')
    reply       = models.BooleanField(verbose_name='Is a reply?', default=False)
    updated     = models.DateTimeField(auto_now=True)
    timestamp   = models.DateTimeField(auto_now_add=True)

    objects = TweetManager()

    def __str__(self):
        return str(self.content)

    def get_absolute_url(self):
        return reverse("tweet:detail", kwargs={"pk":self.pk})

    class Meta:
        ordering = ['-timestamp']

    def get_parent(self):
        the_parent = self
        if self.parent:
            the_parent = self.parent
        return the_parent

    def get_children(self):
        parent = self.get_parent()
        qs = Tweet.objects.filter(parent=parent)
        qs_parent = Tweet.objects.filter(pk=parent.pk)
        return (qs | qs_parent)

    # def clean(self, *args, **kwargs):
    #     content = self.content
    #     if content == "abc":
    #         raise ValidationError("Content cannot be ABC")
    #     return super(Tweet, self).clean(*args, **kwargs)


def tweet_save_receiver(sender, instance, created, *args, **kwargs):
    if created and not instance.parent:
        # notify a user
        user_regex = r'@(?P<username>[\w.@+-]+)'
        usernames = re.findall(user_regex, instance.content)
        # send notification to user here.

        hash_regex = r'#(?P<hashtag>[\w\d-]+)'
        hashtags = re.findall(hash_regex, instance.content)
        parsed_hashtags.send(sender=instance.__class__, hashtag_list=hashtags)
        # send hashtag signal to user here.








post_save.connect(tweet_save_receiver, sender=Tweet)

src/accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()

class UserRegisterForm(forms.Form):
    username = forms.CharField()
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)


    def clean_password2(self):
        password = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password2')
        if password != password2:
            raise forms.ValidationError("Password must match")
        return password2

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username__icontains=username).exists():
            raise forms.ValidationError("This username is taken")
        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email__icontains=email).exists():
            raise forms.ValidationError("This email is already registered.")
        return email

src/accounts/views.py
from django.contrib.auth import get_user_model
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from django.views.generic import DetailView
from django.views.generic.edit import FormView
from .forms import UserRegisterForm
from .models import userProfile


# Create your views here.
User = get_user_model()

class UserRegisterView(FormView):
    template_name = 'accounts/user_register_form.html'
    form_class = UserRegisterForm
    success_url = '/login'

    def form_valid(self, form):
        username = form.cleaned_data.get("username")
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        new_user = User.objects.create(username=username, email=email)
        new_user.set_password(password)
        new_user.save()
        return super(UserRegisterView, self).form_valid(form)

class UserDetailView(DetailView):
	template_name = 'accounts/user_details.html'
	queryset = User.objects.all()
	#slug_field = 'username'
	def get_object(self):
		return get_object_or_404(User, username__iexact=self.kwargs.get("username"))

	def get_context_data(self, *args, **kwargs):
		context = super(UserDetailView, self).get_context_data(*args, **kwargs)
		context['following'] = userProfile.objects.is_following(self.request.user, self.get_object())
		return context


class UserFollowView(View):
	def get(self, request, username, *args, **kwargs):
		toggle_user = get_object_or_404(User, username__iexact=username)
		if request.user.is_authenticated():
			is_following = userProfile.objects.toggle_follow(request.user, toggle_user)
		return redirect("profiles:detail", username=username)

src/accounts/templates/accounts/user_detail.html
{% extends "base.html" %}


{% block script %}
<script>
$(document).ready(function(){
  loadTweetContainer("tweet-container")
});
</script>
{% endblock script %}


{% block content %}
<div class='row'>
    <div class='col-sm-3 col-xs-12'>
        <h1>{{ object.username }} </h1>
        <hr/>
        <p>Followers: {{ object.followed_by.all.count }}</p>
        <p>
            <a class='btn btn-link' href='{{ object.profile.get_follow_url }}'>
                    {% if following %}Unfollow{% else %}Follow{% endif %}
                </a>
        </p>
         <hr/>
          <h1>Following <small>{{ object.profile.get_following.count }}</small></h1>

             {% for user in object.profile.get_following %}
             <a href='/{{ user.username }}'>{{ user.username }}</a><br/>
             {% empty %}
             <h4>Not following any users</h4>
             {% endfor %}

          <hr/>
          <h1>Followed By</h1>
             {% for profile in object.followed_by.all %}
             <a href='/{{ profile.user.username }}'>{{ profile.user.username }}</a><br/>
             {% empty %}
             <h4>Not followed by any users</h4>
             {% endfor %}

          <hr/>
          


    </div>
    <div class='col-sm-9 col-xs-12'>
         <h1>Tweets</h1>
          <div id='tweet-container' data-url='/api/{{ object.username }}/tweet/'>
            
          </div>
          <a href='#' id='loadmore'>Load More Tweets</a>
          
      
        

     </div>

</div>

{% endblock content %}

  

src/accounts/templates/accounts/user_details.html
{% extends "base.html" %}


{% block content %}
<div class="row">
	<div class="col-sm-3" style="background: #4286f4; color: white">
		<h1>{{ object.username }}</h1>
		<hr/>
		<p><a style= "color: white" class="btn btn-link" href='{% url "profiles:follow" username=object.username %}'>{% if following %}Unfollow{% else %}Follow{% endif %}</a></p>
	</div>
	<div class="col-sm-9">
		<h1>User Tweets</h1>
		{% for tweet in object.tweet_set.all %}
		{{ tweet }}<br/>
		{% endfor %}

		<hr/>
		<h1>Following ({{ object.profile.get_following.count }})</h1>
		{% for user in object.profile.get_following %}
		<a href="/{{ user.username }}">{{ user.username }}</a><br/>
		{% empty %}
		<h5>Not Following anyone</h5>
		{% endfor %}

		<hr/>
		<h1>Followed By</h1>
		{% for profile in object.followed_by.all %}
		<a href="/{{ profile.user.username }}">{{ profile.user.username }}</a><br/>
		{% empty %}
		<h5>No Followers</h5>
		{% endfor %}
	</div>
</div>
{% endblock content %}

src/accounts/templates/accounts/user_register_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}


{% block title %}Register | {{ block.super }}{% endblock title %}


{% block content %}
<div class='row'>
    <div class='col-sm-6 col-sm-offset-3'>
        <h1>Register</h1>
                <form class='form {% if form_class %}{{ form_class }}{% endif %}' method='POST' action="{% if action_url %}{{ action_url }}{% endif %}">
           {% csrf_token %}
            {{ form|crispy }}
            <input class='btn btn-primary' type="submit" value="Register" />
        </form>
    </div>
</div>
{% endblock content %}